[package]
name = "clean-genes"
version = "0.2.7"
edition = "2021"


[lints.rust]
# Change to warn before release
dead_code = "allow"

[lints.clippy]
all = "warn"
pedantic = "warn"
allow_attributes = "warn"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
