[package]
name = "clean-genes"
version = "0.2.5"
edition = "2021"


[lints.rust]
# Change to warn before release
dead_code = "allow"

[lints.clippy]
all = "warn"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
